### ISSUE TITLE
Do you have any plans to publish this library to hackage?

### ISSUE THREAD

**Issue by AndrewRademacher** [jeremyjh/distributed-process-lifted#1]

**Comment by jeremyjh** [comment]
I probably will if there is someone who wants it :)

I was happy I had to reimplement one function entirely and I am still a
little on the fence as to whether or not this is a good practice to
encourage but it sure feels more convenient than lift litter.

**Comment by AndrewRademacher** [comment]
The way that you have it implemented is fairly common. Packages like `lifted-async` and `lifted-base` come to mind. I would certainly vote for it being on Hackage.

**Comment by jeremyjh** [comment]
Done!

http://hackage.haskell.org/package/distributed-process-lifted-0.1.0.0
