### ISSUE TITLE
Is there a plan to make the library available on stackage?

### ISSUE THREAD

**Issue by OlivierSohn** [jeremyjh/distributed-process-lifted#2]
I'm asking because I'll use the library for my project which uses stack, it would be a bit more convenient for me if the library was on stackage!

(https://github.com/fpco/stackage/#add-your-package)

**Comment by jeremyjh** [comment]
Yes I can add it. I really had no idea anyone is using this.

**Comment by OlivierSohn** [comment]
Thanks!

**Comment by jeremyjh** [comment]
@OlivierSohn There are a couple of issues here actually. The first is that `network-transport-tcp` is not in Stackage. My library doesn't need that but the tests do. I couldn't even make the latest version of that work the last time I tried, but I probably didn't try very hard. 

The second issue is that `monad-control` and `lifted-base` is probably on its way out. `resourcet` and `conduit` have switched to `unliftio` and that is going to force hundreds of other packages to adopt the same. That will not directly affect this package but I think if I want to put out a version of this package that people can rely on as being stable I should switch to `unliftio` first.

**Comment by jeremyjh** [comment]
Ack, nevermind about the first issue. That was just a broken search I guess.

**Comment by OlivierSohn** [comment]
It makes sense, thanks for the update.

**Comment by jeremyjh** [comment]
@OlivierSohn I ended up changing my mind and added it to Stackage as is, it (and `distributed-process-monad-control`, on which it depends) is available in nightly from 2/26. https://www.stackage.org/nightly-2018-02-26/package/distributed-process-lifted-0.3.0.1
